# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddRow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddRowWindow(object):
    def setupUi(self, AddRowWindow):
        AddRowWindow.setObjectName("AddRowWindow")
        AddRowWindow.resize(307, 174)
        self.id_input = QtWidgets.QTextEdit(AddRowWindow)
        self.id_input.setGeometry(QtCore.QRect(70, 30, 111, 31))
        self.id_input.setObjectName("id_input")
        self.name_input = QtWidgets.QTextEdit(AddRowWindow)
        self.name_input.setGeometry(QtCore.QRect(70, 70, 111, 31))
        self.name_input.setObjectName("name_input")
        self.age_input = QtWidgets.QTextEdit(AddRowWindow)
        self.age_input.setGeometry(QtCore.QRect(70, 110, 111, 31))
        self.age_input.setObjectName("age_input")
        self.label = QtWidgets.QLabel(AddRowWindow)
        self.label.setGeometry(QtCore.QRect(10, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(AddRowWindow)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(AddRowWindow)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.add_row_confirm_btn = QtWidgets.QPushButton(AddRowWindow)
        self.add_row_confirm_btn.setGeometry(QtCore.QRect(200, 60, 75, 51))
        self.add_row_confirm_btn.setObjectName("add_row_confirm_btn")

        self.retranslateUi(AddRowWindow)
        QtCore.QMetaObject.connectSlotsByName(AddRowWindow)

    def retranslateUi(self, AddRowWindow):
        _translate = QtCore.QCoreApplication.translate
        AddRowWindow.setWindowTitle(_translate("AddRowWindow", "Form"))
        self.label.setText(_translate("AddRowWindow", "ID"))
        self.label_2.setText(_translate("AddRowWindow", "Name"))
        self.label_3.setText(_translate("AddRowWindow", "Age"))
        self.add_row_confirm_btn.setText(_translate("AddRowWindow", "Добавить"))
