# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GenerationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(361, 122)
        self.first_btn = QtWidgets.QPushButton(Form)
        self.first_btn.setGeometry(QtCore.QRect(20, 70, 101, 41))
        self.first_btn.setObjectName("first_btn")
        self.second_btn = QtWidgets.QPushButton(Form)
        self.second_btn.setGeometry(QtCore.QRect(130, 70, 101, 41))
        self.second_btn.setObjectName("second_btn")
        self.third_btn = QtWidgets.QPushButton(Form)
        self.third_btn.setGeometry(QtCore.QRect(240, 70, 101, 41))
        self.third_btn.setObjectName("third_btn")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 20, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.first_btn.setText(_translate("Form", "500"))
        self.second_btn.setText(_translate("Form", "1000"))
        self.third_btn.setText(_translate("Form", "5000"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\">Сгенерировать</p></body></html>"))
