# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StepForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Stepform(object):
    def setupUi(self, Stepform):
        Stepform.setObjectName("Stepform")
        Stepform.resize(343, 550)
        self.tableWidget = QtWidgets.QTableWidget(Stepform)
        self.tableWidget.setGeometry(QtCore.QRect(9, 38, 321, 501))
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(99)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.pushButton = QtWidgets.QPushButton(Stepform)
        self.pushButton.setGeometry(QtCore.QRect(9, 9, 101, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Stepform)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 9, 101, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Stepform)
        self.label.setGeometry(QtCore.QRect(110, 10, 121, 20))
        self.label.setObjectName("label")

        self.retranslateUi(Stepform)
        QtCore.QMetaObject.connectSlotsByName(Stepform)

    def retranslateUi(self, Stepform):
        _translate = QtCore.QCoreApplication.translate
        Stepform.setWindowTitle(_translate("Stepform", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Stepform", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Stepform", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Stepform", "Age"))
        self.pushButton.setText(_translate("Stepform", "Пред"))
        self.pushButton_2.setText(_translate("Stepform", "След"))
        self.label.setText(_translate("Stepform", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Шаг: 1</span></p></body></html>"))
